name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    container: epitechcontent/epitest-docker
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: make tests_run
